### ISSUE TITLE
UAE timings

### ISSUE THREAD

**Issue by jumeira** [DPANET/PrayersHomeySDK3#12]
Hi Omar
First of all thanks for your efforts by bringing prayer alerts to homey, I have tried the app recently for play athan in my home. I am having an issue where i cant set the prayers timings perfectly here in UAE, Dubai.. our calculation method is different and every hijri calander year our islamic affairs issue the timing for 1 or 2 years in advance, i have dedicated server where i update the timings when ever they got updated and upload them into my server, after that we use rpi to play athan.. but the issue is we need to maintain the script from time to time. So please can we find a solution for UAE timings with your app please? I can help you with everything you need. Here is the link where we direct the rpi to read the timing when ever is the timing for a prayer is matched:
https://belquhood.com/me/getTodayAzan_dubai

**Comment by DPANET** [comment]
The app use this api to calculate the athan , I'm relaying on this API maintain [Athan Prayers API](https://aladhan.com/prayer-times-api) , it is well maintained API and the owner is in lives in Dubai as well, I recommend you reach out to him to figure out a way to load the UAE timing calendar.

The best way is to rely on the api provided by Awqaf in Abu Dhabi, unfortunately, they do not offer their APIs to public and you need to be an official company to gain access, I tried to contact them a punch of times but that did not work.

in the meanwhile you can rely on the app to adjust the timing, usually they're off by a min or 2 on a week to week basis, I know it is not optimal, but better than nothing.

**Comment by jumeira** [comment]
Hi Omar,

I have been in touch with the guy who handles the Athan website, he was very helpful and he figured out how to make work for UAE timings, he added the calculation method (no.16) on this link:
https://aladhan.com/calculation-methods

direct link for the api:
https://api.aladhan.com/v1/timingsByCity?city=Dubai&country=UAE&method=16

I hope this make sense and will help us for UAE timings on the app.

**Comment by DPANET** [comment]
noted, it seems I hard coded the methods in the app instead of relying on the api call, will reflect the changes hopefully this week

**Comment by DPANET** [comment]
the modification did and released update the app to get the new Dubai method
