### ISSUE TITLE
Can't get location coordinates 

### ISSUE THREAD

**Issue by jumeira** [DPANET/PrayersHomeySDK3#18]
I am trying to use the app on my HP23, but I am not able to get coordinates nor city location after making the search for the location, please check the images attached. Tried reinstalling the app but the same issue occurs, if I save i get the error msg below or even if I view the timings, the reset don't do anything.

![prayersalert](https://user-images.githubusercontent.com/57864462/230430943-861497de-62b4-4805-95df-a72b71fcd27a.jpg)

![prayersalert1](https://user-images.githubusercontent.com/57864462/230431310-410b1b6e-5bcc-46cd-80d7-030aa8ae3045.jpg)

![prayersalert2](https://user-images.githubusercontent.com/57864462/230431015-5dc911ae-e02b-4714-9571-9d5219f502b8.jpg)

**Comment by DPANET** [comment]
Unfortunately, I cannot reproduce the error, you are running a beta version of homey which only works in HP23, I'm waiting for my unit to arrive once I have it I will be able to simulate the error.

**Comment by jumeira** [comment]
No worries at all, hope you get it asap, hp23 is a monster.

**Comment by DPANET** [comment]
I got the unit today and fixed the bug the app is live you can run it
